# frozen_string_literal: true

module Columns
  class FeedForm < BaseForm
    DEFAULTS = %w[id advertiser_name name offers_count succeeded_at created_at].freeze

    self.all_columns = [
      { key: 'id'                                              , pg: Feed.columns_hash['id'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'operation'                                       , pg: Feed.columns_hash['operation'], roles: ['admin'] },
      { key: 'ext_id'                                          , pg: Feed.columns_hash['ext_id'], roles: ['admin'] },
      { key: 'name'                                            , pg: Feed.columns_hash['name'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'url'                                             , pg: Feed.columns_hash['url'], roles: ['admin'] },
      { key: 'error_class'                                     , pg: Feed.columns_hash['error_class'], roles: ['admin'] },
      { key: 'error_text'                                      , pg: Feed.columns_hash['error_text'], roles: ['admin'] },
      { key: 'locked_by_pid'                                   , pg: Feed.columns_hash['locked_by_pid'], roles: ['admin'] },
      { key: 'language'                                        , pg: Feed.columns_hash['language'], roles: ['admin'] },
      { key: 'attempt_uuid'                                    , pg: Feed.columns_hash['attempt_uuid'], roles: ['admin'] },
      { key: 'raw'                                             , pg: Feed.columns_hash['raw'], roles: ['admin'] },
      { key: 'processing_started_at'                           , pg: Feed.columns_hash['processing_started_at'], roles: ['admin'] },
      { key: 'processing_finished_at'                          , pg: Feed.columns_hash['processing_finished_at'], roles: ['admin'] },
      { key: 'synced_at'                                       , pg: Feed.columns_hash['synced_at'], roles: ['admin'] },
      { key: 'network_updated_at'                              , pg: Feed.columns_hash['network_updated_at'], roles: ['admin'] },
      { key: 'categories_count'                                , pg: Feed.columns_hash['categories_count'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'offers_count'                                    , pg: Feed.columns_hash['offers_count'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'priority'                                        , pg: Feed.columns_hash['priority'], roles: ['admin'] },
      { key: 'xml_file_path'                                   , pg: Feed.columns_hash['xml_file_path'], roles: ['admin'] },
      { key: 'downloaded_file_type'                            , pg: Feed.columns_hash['downloaded_file_type'], roles: ['admin'] },
      { key: 'is_active'                                       , pg: Feed.columns_hash['is_active'], roles: ['admin'] },
      { key: 'downloaded_file_size'                            , pg: Feed.columns_hash['downloaded_file_size'], roles: ['admin'] },

      { key: 'advertiser_id'                                   , pg: Advertiser.columns_hash['id'], roles: ['admin'] },
      { key: 'advertiser_type'                                 , pg: Advertiser.columns_hash['type'], roles: ['admin'] },
      { key: 'advertiser_ext_id'                               , pg: Advertiser.columns_hash['ext_id'], roles: ['admin'] },
      { key: 'advertiser_raw'                                  , pg: Advertiser.columns_hash['raw'], roles: ['admin'] },
      { key: 'advertiser_synced_at'                            , pg: Advertiser.columns_hash['synced_at'], roles: ['admin'] },
      { key: 'advertiser_created_at'                           , pg: Advertiser.columns_hash['created_at'], roles: ['admin'] },
      { key: 'advertiser_updated_at'                           , pg: Advertiser.columns_hash['updated_at'], roles: ['admin'] },
      { key: 'advertiser_name'                                 , pg: Advertiser.columns_hash['name'], roles: ['guest', 'user', 'manager', 'admin'] },

      { key: 'advertiser_gdeslon_id'                           , pg: Advertiser.columns_hash['gdeslon_id'], roles: ['admin'] },
      { key: 'advertiser_gdeslon_name'                         , pg: Advertiser.columns_hash['gdeslon_name'], roles: ['admin'] },
      { key: 'advertiser_gdeslon_short_description'            , pg: Advertiser.columns_hash['gdeslon_short_description'], roles: ['admin'] },
      { key: 'advertiser_gdeslon_description'                  , pg: Advertiser.columns_hash['gdeslon_description'], roles: ['admin'] },
      { key: 'advertiser_gdeslon_url'                          , pg: Advertiser.columns_hash['gdeslon_url'], roles: ['admin'] },
      { key: 'advertiser_gdeslon_conditions'                   , pg: Advertiser.columns_hash['gdeslon_conditions'], roles: ['admin'] },
      { key: 'advertiser_gdeslon_is_green'                     , pg: Advertiser.columns_hash['gdeslon_is_green'], roles: ['admin'] },
      { key: 'advertiser_gdeslon_gs_commission_mark'           , pg: Advertiser.columns_hash['gdeslon_gs_commission_mark'], roles: ['admin'] },
      { key: 'advertiser_gdeslon_country'                      , pg: Advertiser.columns_hash['gdeslon_country'], roles: ['admin'] },
      { key: 'advertiser_gdeslon_kind'                         , pg: Advertiser.columns_hash['gdeslon_kind'], roles: ['admin'] },
      { key: 'advertiser_gdeslon_categories'                   , pg: Advertiser.columns_hash['gdeslon_categories'], roles: ['admin'] },
      { key: 'advertiser_gdeslon_logo_file_name'               , pg: Advertiser.columns_hash['gdeslon_logo_file_name'], roles: ['admin'] },
      { key: 'advertiser_gdeslon_affiliate_link'               , pg: Advertiser.columns_hash['gdeslon_affiliate_link'], roles: ['admin'] },
      { key: 'advertiser_gdeslon_traffic_types'                , pg: Advertiser.columns_hash['gdeslon_traffic_types'], roles: ['admin'] },
      { key: 'advertiser_gdeslon_tariffs'                      , pg: Advertiser.columns_hash['gdeslon_tariffs'], roles: ['admin'] },

      { key: 'advertiser_admitad_id'                           , pg: Advertiser.columns_hash['admitad_id'], roles: ['admin'] },
      { key: 'advertiser_admitad_name'                         , pg: Advertiser.columns_hash['admitad_name'], roles: ['admin'] },
      { key: 'advertiser_admitad_site_url'                     , pg: Advertiser.columns_hash['admitad_site_url'], roles: ['admin'] },
      { key: 'advertiser_admitad_description'                  , pg: Advertiser.columns_hash['admitad_description'], roles: ['admin'] },
      { key: 'advertiser_admitad_raw_description'              , pg: Advertiser.columns_hash['admitad_raw_description'], roles: ['admin'] },
      { key: 'advertiser_admitad_currency'                     , pg: Advertiser.columns_hash['admitad_currency'], roles: ['admin'] },
      { key: 'advertiser_admitad_rating'                       , pg: Advertiser.columns_hash['admitad_rating'], roles: ['admin'] },
      { key: 'advertiser_admitad_ecpc'                         , pg: Advertiser.columns_hash['admitad_ecpc'], roles: ['admin'] },
      { key: 'advertiser_admitad_epc'                          , pg: Advertiser.columns_hash['admitad_epc'], roles: ['admin'] },
      { key: 'advertiser_admitad_cr'                           , pg: Advertiser.columns_hash['admitad_cr'], roles: ['admin'] },
      { key: 'advertiser_admitad_actions'                      , pg: Advertiser.columns_hash['admitad_actions'], roles: ['admin'] },
      { key: 'advertiser_admitad_regions'                      , pg: Advertiser.columns_hash['admitad_regions'], roles: ['admin'] },
      { key: 'advertiser_admitad_categories'                   , pg: Advertiser.columns_hash['admitad_categories'], roles: ['admin'] },
      { key: 'advertiser_admitad_status'                       , pg: Advertiser.columns_hash['admitad_status'], roles: ['admin'] },
      { key: 'advertiser_admitad_image'                        , pg: Advertiser.columns_hash['admitad_image'], roles: ['admin'] },
      { key: 'advertiser_admitad_ecpc_trend'                   , pg: Advertiser.columns_hash['admitad_ecpc_trend'], roles: ['admin'] },
      { key: 'advertiser_admitad_epc_trend'                    , pg: Advertiser.columns_hash['admitad_epc_trend'], roles: ['admin'] },
      { key: 'advertiser_admitad_cr_trend'                     , pg: Advertiser.columns_hash['admitad_cr_trend'], roles: ['admin'] },
      { key: 'advertiser_admitad_exclusive'                    , pg: Advertiser.columns_hash['admitad_exclusive'], roles: ['admin'] },
      { key: 'advertiser_admitad_activation_date'              , pg: Advertiser.columns_hash['admitad_activation_date'], roles: ['admin'] },
      { key: 'advertiser_admitad_modified_date'                , pg: Advertiser.columns_hash['admitad_modified_date'], roles: ['admin'] },
      { key: 'advertiser_admitad_denynewwms'                   , pg: Advertiser.columns_hash['admitad_denynewwms'], roles: ['admin'] },
      { key: 'advertiser_admitad_goto_cookie_lifetime'         , pg: Advertiser.columns_hash['admitad_goto_cookie_lifetime'], roles: ['admin'] },
      { key: 'advertiser_admitad_retag'                        , pg: Advertiser.columns_hash['admitad_retag'], roles: ['admin'] },
      { key: 'advertiser_admitad_show_products_links'          , pg: Advertiser.columns_hash['admitad_show_products_links'], roles: ['admin'] },
      { key: 'advertiser_admitad_landing_code'                 , pg: Advertiser.columns_hash['admitad_landing_code'], roles: ['admin'] },
      { key: 'advertiser_admitad_landing_title'                , pg: Advertiser.columns_hash['admitad_landing_title'], roles: ['admin'] },
      { key: 'advertiser_admitad_geotargeting'                 , pg: Advertiser.columns_hash['admitad_geotargeting'], roles: ['admin'] },
      { key: 'advertiser_admitad_max_hold_time'                , pg: Advertiser.columns_hash['admitad_max_hold_time'], roles: ['admin'] },
      { key: 'advertiser_admitad_traffics'                     , pg: Advertiser.columns_hash['admitad_traffics'], roles: ['admin'] },
      { key: 'advertiser_admitad_avg_hold_time'                , pg: Advertiser.columns_hash['admitad_avg_hold_time'], roles: ['admin'] },
      { key: 'advertiser_admitad_avg_money_transfer_time'      , pg: Advertiser.columns_hash['admitad_avg_money_transfer_time'], roles: ['admin'] },
      { key: 'advertiser_admitad_allow_deeplink'               , pg: Advertiser.columns_hash['admitad_allow_deeplink'], roles: ['admin'] },
      { key: 'advertiser_admitad_coupon_iframe_denied'         , pg: Advertiser.columns_hash['admitad_coupon_iframe_denied'], roles: ['admin'] },
      { key: 'advertiser_admitad_action_testing_limit'         , pg: Advertiser.columns_hash['admitad_action_testing_limit'], roles: ['admin'] },
      { key: 'advertiser_admitad_mobile_device_type'           , pg: Advertiser.columns_hash['admitad_mobile_device_type'], roles: ['admin'] },
      { key: 'advertiser_admitad_mobile_os'                    , pg: Advertiser.columns_hash['admitad_mobile_os'], roles: ['admin'] },
      { key: 'advertiser_admitad_mobile_os_type'               , pg: Advertiser.columns_hash['admitad_mobile_os_type'], roles: ['admin'] },
      { key: 'advertiser_admitad_action_countries'             , pg: Advertiser.columns_hash['admitad_action_countries'], as: :string, roles: ['admin'] },
      { key: 'advertiser_admitad_allow_actions_all_countries'  , pg: Advertiser.columns_hash['admitad_allow_actions_all_countries'], roles: ['admin'] },
      { key: 'advertiser_admitad_connection_status'            , pg: Advertiser.columns_hash['admitad_connection_status'], roles: ['admin'] },
      { key: 'advertiser_admitad_gotolink'                     , pg: Advertiser.columns_hash['admitad_gotolink'], roles: ['admin'] },
      { key: 'advertiser_admitad_products_xml_link'            , pg: Advertiser.columns_hash['admitad_products_xml_link'], roles: ['admin'] },
      { key: 'advertiser_admitad_products_csv_link'            , pg: Advertiser.columns_hash['admitad_products_csv_link'], roles: ['admin'] },
      { key: 'advertiser_admitad_moderation'                   , pg: Advertiser.columns_hash['admitad_moderation'], roles: ['admin'] },
      { key: 'advertiser_admitad_feeds_info'                   , pg: Advertiser.columns_hash['admitad_feeds_info'], roles: ['admin'] },
      { key: 'advertiser_admitad_actions_detail'               , pg: Advertiser.columns_hash['admitad_actions_detail'], roles: ['admin'] },
      { key: 'advertiser_admitad_actions_limit'                , pg: Advertiser.columns_hash['admitad_actions_limit'], roles: ['admin'] },
      { key: 'advertiser_admitad_actions_limit_24'             , pg: Advertiser.columns_hash['admitad_actions_limit_24'], roles: ['admin'] },

      { key: 'succeeded_at'                                    , pg: Feed.columns_hash['succeeded_at'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'network_updated_at'                              , pg: Feed.columns_hash['network_updated_at'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_updated_at'                           , pg: Feed.columns_hash['advertiser_updated_at'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'offers_count'                                    , pg: Feed.columns_hash['offers_count'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'categories_count'                                , pg: Feed.columns_hash['categories_count'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'priority'                                        , pg: Feed.columns_hash['priority'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'xml_file_path'                                   , pg: Feed.columns_hash['xml_file_path'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'downloaded_file_type'                            , pg: Feed.columns_hash['downloaded_file_type'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'is_active'                                       , pg: Feed.columns_hash['is_active'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'downloaded_file_size'                            , pg: Feed.columns_hash['downloaded_file_size'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'created_at'                                      , pg: Feed.columns_hash['created_at'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'updated_at'                                      , pg: Feed.columns_hash['updated_at'], roles: ['guest', 'user', 'manager', 'admin'] },

      { key: 'advertiser_id'                                   , pg: Advertiser.columns_hash['id'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_type'                                 , pg: Advertiser.columns_hash['type'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_ext_id'                               , pg: Advertiser.columns_hash['ext_id'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_name'                                 , pg: Advertiser.columns_hash['name'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_data'                                 , pg: Advertiser.columns_hash['data'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_synced_at'                            , pg: Advertiser.columns_hash['synced_at'], roles: ['guest', 'user', 'manager', 'admin'] },

      { key: 'advertiser_gdeslon_id'                           , pg: Advertiser.columns_hash['gdeslon_id'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_gdeslon_name'                         , pg: Advertiser.columns_hash['gdeslon_name'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_gdeslon_short_description'            , pg: Advertiser.columns_hash['gdeslon_short_description'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_gdeslon_description'                  , pg: Advertiser.columns_hash['gdeslon_description'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_gdeslon_url'                          , pg: Advertiser.columns_hash['gdeslon_url'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_gdeslon_conditions'                   , pg: Advertiser.columns_hash['gdeslon_conditions'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_gdeslon_is_green'                     , pg: Advertiser.columns_hash['gdeslon_is_green'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_gdeslon_gs_commission_mark'           , pg: Advertiser.columns_hash['gdeslon_gs_commission_mark'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_gdeslon_country'                      , pg: Advertiser.columns_hash['gdeslon_country'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_gdeslon_kind'                         , pg: Advertiser.columns_hash['gdeslon_kind'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_gdeslon_categories'                   , pg: Advertiser.columns_hash['gdeslon_categories'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_gdeslon_logo_file_name'               , pg: Advertiser.columns_hash['gdeslon_logo_file_name'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_gdeslon_affiliate_link'               , pg: Advertiser.columns_hash['gdeslon_affiliate_link'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_gdeslon_traffic_types'                , pg: Advertiser.columns_hash['gdeslon_traffic_types'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_gdeslon_tariffs'                      , pg: Advertiser.columns_hash['gdeslon_tariffs'], roles: ['guest', 'user', 'manager', 'admin'] },

      { key: 'advertiser_admitad_id'                           , pg: Advertiser.columns_hash['admitad_id'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_name'                         , pg: Advertiser.columns_hash['admitad_name'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_site_url'                     , pg: Advertiser.columns_hash['admitad_site_url'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_description'                  , pg: Advertiser.columns_hash['admitad_description'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_raw_description'              , pg: Advertiser.columns_hash['admitad_raw_description'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_currency'                     , pg: Advertiser.columns_hash['admitad_currency'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_rating'                       , pg: Advertiser.columns_hash['admitad_rating'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_ecpc'                         , pg: Advertiser.columns_hash['admitad_ecpc'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_epc'                          , pg: Advertiser.columns_hash['admitad_epc'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_cr'                           , pg: Advertiser.columns_hash['admitad_cr'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_actions'                      , pg: Advertiser.columns_hash['admitad_actions'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_regions'                      , pg: Advertiser.columns_hash['admitad_regions'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_categories'                   , pg: Advertiser.columns_hash['admitad_categories'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_status'                       , pg: Advertiser.columns_hash['admitad_status'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_image'                        , pg: Advertiser.columns_hash['admitad_image'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_ecpc_trend'                   , pg: Advertiser.columns_hash['admitad_ecpc_trend'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_epc_trend'                    , pg: Advertiser.columns_hash['admitad_epc_trend'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_cr_trend'                     , pg: Advertiser.columns_hash['admitad_cr_trend'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_exclusive'                    , pg: Advertiser.columns_hash['admitad_exclusive'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_activation_date'              , pg: Advertiser.columns_hash['admitad_activation_date'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_modified_date'                , pg: Advertiser.columns_hash['admitad_modified_date'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_denynewwms'                   , pg: Advertiser.columns_hash['admitad_denynewwms'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_goto_cookie_lifetime'         , pg: Advertiser.columns_hash['admitad_goto_cookie_lifetime'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_retag'                        , pg: Advertiser.columns_hash['admitad_retag'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_show_products_links'          , pg: Advertiser.columns_hash['admitad_show_products_links'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_landing_code'                 , pg: Advertiser.columns_hash['admitad_landing_code'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_landing_title'                , pg: Advertiser.columns_hash['admitad_landing_title'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_geotargeting'                 , pg: Advertiser.columns_hash['admitad_geotargeting'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_max_hold_time'                , pg: Advertiser.columns_hash['admitad_max_hold_time'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_traffics'                     , pg: Advertiser.columns_hash['admitad_traffics'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_avg_hold_time'                , pg: Advertiser.columns_hash['admitad_avg_hold_time'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_avg_money_transfer_time'      , pg: Advertiser.columns_hash['admitad_avg_money_transfer_time'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_allow_deeplink'               , pg: Advertiser.columns_hash['admitad_allow_deeplink'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_coupon_iframe_denied'         , pg: Advertiser.columns_hash['admitad_coupon_iframe_denied'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_action_testing_limit'         , pg: Advertiser.columns_hash['admitad_action_testing_limit'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_mobile_device_type'           , pg: Advertiser.columns_hash['admitad_mobile_device_type'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_mobile_os'                    , pg: Advertiser.columns_hash['admitad_mobile_os'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_mobile_os_type'               , pg: Advertiser.columns_hash['admitad_mobile_os_type'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_action_countries'             , pg: Advertiser.columns_hash['admitad_action_countries'], as: :string, roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_allow_actions_all_countries'  , pg: Advertiser.columns_hash['admitad_allow_actions_all_countries'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_connection_status'            , pg: Advertiser.columns_hash['admitad_connection_status'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_gotolink'                     , pg: Advertiser.columns_hash['admitad_gotolink'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_products_xml_link'            , pg: Advertiser.columns_hash['admitad_products_xml_link'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_products_csv_link'            , pg: Advertiser.columns_hash['admitad_products_csv_link'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_moderation'                   , pg: Advertiser.columns_hash['admitad_moderation'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_feeds_info'                   , pg: Advertiser.columns_hash['admitad_feeds_info'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_actions_detail'               , pg: Advertiser.columns_hash['admitad_actions_detail'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_actions_limit'                , pg: Advertiser.columns_hash['admitad_actions_limit'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_admitad_actions_limit_24'             , pg: Advertiser.columns_hash['admitad_actions_limit_24'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_created_at'                           , pg: Advertiser.columns_hash['created_at'], roles: ['guest', 'user', 'manager', 'admin'] },
      { key: 'advertiser_updated_at'                           , pg: Advertiser.columns_hash['updated_at'], roles: ['guest', 'user', 'manager', 'admin'] }
    ]
  end
end
