# frozen_string_literal: true

module Columns
  class FeedForm < BaseForm
    DEFAULTS = %w[id advertiser_name name].freeze

    self.all_columns = [
      { key: 'id'                                              , pg: Feed.columns_hash['id'] },
      { key: 'operation'                                       , pg: Feed.columns_hash['operation'] },
      { key: 'ext_id'                                          , pg: Feed.columns_hash['ext_id'] },
      { key: 'name'                                            , pg: Feed.columns_hash['name'] },
      { key: 'url'                                             , pg: Feed.columns_hash['url'] },
      { key: 'error_class'                                     , pg: Feed.columns_hash['error_class'] },
      { key: 'error_text'                                      , pg: Feed.columns_hash['error_text'] },
      { key: 'locked_by_pid'                                   , pg: Feed.columns_hash['locked_by_pid'] },
      { key: 'language'                                        , pg: Feed.columns_hash['language'] },
      { key: 'index_name'                                      , pg: Feed.columns_hash['index_name'] },
      { key: 'attempt_uuid'                                    , pg: Feed.columns_hash['attempt_uuid'] },
      { key: 'data'                                            , pg: Feed.columns_hash['data'] },
      { key: 'processing_started_at'                           , pg: Feed.columns_hash['processing_started_at'] },
      { key: 'processing_finished_at'                          , pg: Feed.columns_hash['processing_finished_at'] },
      { key: 'synced_at'                                       , pg: Feed.columns_hash['synced_at'] },
      { key: 'succeeded_at'                                    , pg: Feed.columns_hash['succeeded_at'] },
      { key: 'network_updated_at'                              , pg: Feed.columns_hash['network_updated_at'] },
      { key: 'advertiser_updated_at'                           , pg: Feed.columns_hash['advertiser_updated_at'] },
      { key: 'offers_count'                                    , pg: Feed.columns_hash['offers_count'] },
      { key: 'categories_count'                                , pg: Feed.columns_hash['categories_count'] },
      { key: 'priority'                                        , pg: Feed.columns_hash['priority'] },
      { key: 'xml_file_path'                                   , pg: Feed.columns_hash['xml_file_path'] },
      { key: 'downloaded_file_type'                            , pg: Feed.columns_hash['downloaded_file_type'] },
      { key: 'is_active'                                       , pg: Feed.columns_hash['is_active'] },
      { key: 'downloaded_file_size'                            , pg: Feed.columns_hash['downloaded_file_size'] },
      { key: 'created_at'                                      , pg: Feed.columns_hash['created_at'] },
      { key: 'updated_at'                                      , pg: Feed.columns_hash['updated_at'] },

      { key: 'advertiser_id'                                   , pg: Advertiser.columns_hash['id'] },
      { key: 'advertiser_type'                                 , pg: Advertiser.columns_hash['type'] },
      { key: 'advertiser_ext_id'                               , pg: Advertiser.columns_hash['ext_id'] },
      { key: 'advertiser_name'                                 , pg: Advertiser.columns_hash['name'] },
      { key: 'advertiser_data'                                 , pg: Advertiser.columns_hash['data'] },
      { key: 'advertiser_synced_at'                            , pg: Advertiser.columns_hash['synced_at'] },

      { key: 'advertiser_gdeslon_id'                           , pg: Advertiser.columns_hash['gdeslon_id'] },
      { key: 'advertiser_gdeslon_name'                         , pg: Advertiser.columns_hash['gdeslon_name'] },
      { key: 'advertiser_gdeslon_short_description'            , pg: Advertiser.columns_hash['gdeslon_short_description'] },
      { key: 'advertiser_gdeslon_description'                  , pg: Advertiser.columns_hash['gdeslon_description'] },
      { key: 'advertiser_gdeslon_url'                          , pg: Advertiser.columns_hash['gdeslon_url'] },
      { key: 'advertiser_gdeslon_conditions'                   , pg: Advertiser.columns_hash['gdeslon_conditions'] },
      { key: 'advertiser_gdeslon_is_green'                     , pg: Advertiser.columns_hash['gdeslon_is_green'] },
      { key: 'advertiser_gdeslon_gs_commission_mark'           , pg: Advertiser.columns_hash['gdeslon_gs_commission_mark'] },
      { key: 'advertiser_gdeslon_country'                      , pg: Advertiser.columns_hash['gdeslon_country'] },
      { key: 'advertiser_gdeslon_kind'                         , pg: Advertiser.columns_hash['gdeslon_kind'] },
      { key: 'advertiser_gdeslon_categories'                   , pg: Advertiser.columns_hash['gdeslon_categories'] },
      { key: 'advertiser_gdeslon_logo_file_name'               , pg: Advertiser.columns_hash['gdeslon_logo_file_name'] },
      { key: 'advertiser_gdeslon_affiliate_link'               , pg: Advertiser.columns_hash['gdeslon_affiliate_link'] },
      { key: 'advertiser_gdeslon_traffic_types'                , pg: Advertiser.columns_hash['gdeslon_traffic_types'] },
      { key: 'advertiser_gdeslon_tariffs'                      , pg: Advertiser.columns_hash['gdeslon_tariffs'] },

      { key: 'advertiser_admitad_id'                           , pg: Advertiser.columns_hash['admitad_id'] },
      { key: 'advertiser_admitad_name'                         , pg: Advertiser.columns_hash['admitad_name'] },
      { key: 'advertiser_admitad_site_url'                     , pg: Advertiser.columns_hash['admitad_site_url'] },
      { key: 'advertiser_admitad_description'                  , pg: Advertiser.columns_hash['admitad_description'] },
      { key: 'advertiser_admitad_raw_description'              , pg: Advertiser.columns_hash['admitad_raw_description'] },
      { key: 'advertiser_admitad_currency'                     , pg: Advertiser.columns_hash['admitad_currency'] },
      { key: 'advertiser_admitad_rating'                       , pg: Advertiser.columns_hash['admitad_rating'] },
      { key: 'advertiser_admitad_ecpc'                         , pg: Advertiser.columns_hash['admitad_ecpc'] },
      { key: 'advertiser_admitad_epc'                          , pg: Advertiser.columns_hash['admitad_epc'] },
      { key: 'advertiser_admitad_cr'                           , pg: Advertiser.columns_hash['admitad_cr'] },
      { key: 'advertiser_admitad_actions'                      , pg: Advertiser.columns_hash['admitad_actions'] },
      { key: 'advertiser_admitad_regions'                      , pg: Advertiser.columns_hash['admitad_regions'] },
      { key: 'advertiser_admitad_categories'                   , pg: Advertiser.columns_hash['admitad_categories'] },
      { key: 'advertiser_admitad_status'                       , pg: Advertiser.columns_hash['admitad_status'] },
      { key: 'advertiser_admitad_image'                        , pg: Advertiser.columns_hash['admitad_image'] },
      { key: 'advertiser_admitad_ecpc_trend'                   , pg: Advertiser.columns_hash['admitad_ecpc_trend'] },
      { key: 'advertiser_admitad_epc_trend'                    , pg: Advertiser.columns_hash['admitad_epc_trend'] },
      { key: 'advertiser_admitad_cr_trend'                     , pg: Advertiser.columns_hash['admitad_cr_trend'] },
      { key: 'advertiser_admitad_exclusive'                    , pg: Advertiser.columns_hash['admitad_exclusive'] },
      { key: 'advertiser_admitad_activation_date'              , pg: Advertiser.columns_hash['admitad_activation_date'] },
      { key: 'advertiser_admitad_modified_date'                , pg: Advertiser.columns_hash['admitad_modified_date'] },
      { key: 'advertiser_admitad_denynewwms'                   , pg: Advertiser.columns_hash['admitad_denynewwms'] },
      { key: 'advertiser_admitad_goto_cookie_lifetime'         , pg: Advertiser.columns_hash['admitad_goto_cookie_lifetime'] },
      { key: 'advertiser_admitad_retag'                        , pg: Advertiser.columns_hash['admitad_retag'] },
      { key: 'advertiser_admitad_show_products_links'          , pg: Advertiser.columns_hash['admitad_show_products_links'] },
      { key: 'advertiser_admitad_landing_code'                 , pg: Advertiser.columns_hash['admitad_landing_code'] },
      { key: 'advertiser_admitad_landing_title'                , pg: Advertiser.columns_hash['admitad_landing_title'] },
      { key: 'advertiser_admitad_geotargeting'                 , pg: Advertiser.columns_hash['admitad_geotargeting'] },
      { key: 'advertiser_admitad_max_hold_time'                , pg: Advertiser.columns_hash['admitad_max_hold_time'] },
      { key: 'advertiser_admitad_traffics'                     , pg: Advertiser.columns_hash['admitad_traffics'] },
      { key: 'advertiser_admitad_avg_hold_time'                , pg: Advertiser.columns_hash['admitad_avg_hold_time'] },
      { key: 'advertiser_admitad_avg_money_transfer_time'      , pg: Advertiser.columns_hash['admitad_avg_money_transfer_time'] },
      { key: 'advertiser_admitad_allow_deeplink'               , pg: Advertiser.columns_hash['admitad_allow_deeplink'] },
      { key: 'advertiser_admitad_coupon_iframe_denied'         , pg: Advertiser.columns_hash['admitad_coupon_iframe_denied'] },
      { key: 'advertiser_admitad_action_testing_limit'         , pg: Advertiser.columns_hash['admitad_action_testing_limit'] },
      { key: 'advertiser_admitad_mobile_device_type'           , pg: Advertiser.columns_hash['admitad_mobile_device_type'] },
      { key: 'advertiser_admitad_mobile_os'                    , pg: Advertiser.columns_hash['admitad_mobile_os'] },
      { key: 'advertiser_admitad_mobile_os_type'               , pg: Advertiser.columns_hash['admitad_mobile_os_type'] },
      { key: 'advertiser_admitad_action_countries'             , pg: Advertiser.columns_hash['admitad_action_countries'], as: :string },
      { key: 'advertiser_admitad_allow_actions_all_countries'  , pg: Advertiser.columns_hash['admitad_allow_actions_all_countries'] },
      { key: 'advertiser_admitad_connection_status'            , pg: Advertiser.columns_hash['admitad_connection_status'] },
      { key: 'advertiser_admitad_gotolink'                     , pg: Advertiser.columns_hash['admitad_gotolink'] },
      { key: 'advertiser_admitad_products_xml_link'            , pg: Advertiser.columns_hash['admitad_products_xml_link'] },
      { key: 'advertiser_admitad_products_csv_link'            , pg: Advertiser.columns_hash['admitad_products_csv_link'] },
      { key: 'advertiser_admitad_moderation'                   , pg: Advertiser.columns_hash['admitad_moderation'] },
      { key: 'advertiser_admitad_feeds_info'                   , pg: Advertiser.columns_hash['admitad_feeds_info'] },
      { key: 'advertiser_admitad_actions_detail'               , pg: Advertiser.columns_hash['admitad_actions_detail'] },
      { key: 'advertiser_admitad_actions_limit'                , pg: Advertiser.columns_hash['admitad_actions_limit'] },
      { key: 'advertiser_admitad_actions_limit_24'             , pg: Advertiser.columns_hash['admitad_actions_limit_24'] },
      { key: 'advertiser_created_at'                           , pg: Advertiser.columns_hash['created_at'] },
      { key: 'advertiser_updated_at'                           , pg: Advertiser.columns_hash['updated_at'] }
    ]
  end
end
