image: docker/compose:latest

services:
  - docker:dind

stages:
  - build
  - test

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - mv $CI_PROJECT_DIR/.env.gitlab $CI_PROJECT_DIR/.env
  - chmod 600 $CI_PROJECT_DIR/docker/traefik/letsencrypt/acme.json

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.engineer.yml pull
    - docker-compose -f docker-compose.yml -f docker-compose.engineer.yml build
    - docker-compose -f docker-compose.yml -f docker-compose.engineer.yml push
    - export version=$CI_COMMIT_SHORT_SHA
    - docker-compose -f docker-compose.yml -f docker-compose.engineer.yml build
    - docker-compose -f docker-compose.yml -f docker-compose.engineer.yml push
  tags:
    - docker

rubocop:
  stage: test
  script:
    - export version=$CI_COMMIT_SHORT_SHA
    - docker-compose -f docker-compose.yml -f docker-compose.engineer.yml pull
    - docker-compose -f docker-compose.yml run --rm rails bundle exec rubocop
  tags:
    - docker

rspec:
  stage: test
  script:
    - export version=$CI_COMMIT_SHORT_SHA
    - docker-compose -f docker-compose.yml -f docker-compose.engineer.yml pull
    - docker-compose -f docker-compose.yml up -d traefik postgres redis_oauth redis_cable redis_cache elastic
    - docker-compose -f docker-compose.yml run --rm rails bundle exec rake db:test:prepare
    - docker-compose -f docker-compose.yml run --rm rails bundle exec rspec
  tags:
    - docker

puppeteer:
  stage: test
  script:
    - export version=$CI_COMMIT_SHORT_SHA
    - docker-compose -f docker-compose.yml -f docker-compose.engineer.yml pull
    - docker-compose -f docker-compose.yml up -d traefik postgres redis_oauth redis_cable redis_cache rails elastic
    - docker-compose -f docker-compose.yml run --rm rails bundle exec rake db:setup
    - docker-compose -f docker-compose.yml -f docker-compose.engineer.yml run --rm alpine sh -c "curl https://\$DOMAIN_NAME"
    - docker-compose -f docker-compose.yml -f docker-compose.engineer.yml run --rm alpine sh -c "curl https://\$DOMAIN_NAME/api/v1/staff/seeder/elastic/pagination"
    - docker-compose -f docker-compose.yml run --rm puppeteer
  tags:
    - docker
