image: docker:latest

variables:
  HUB_ENV: "test"

services:
  - docker:dind

before_script:
  - docker info
  - apk add py-pip
  - apk add python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose

build:
  stage: build
  script:
    - chmod 600 $CI_PROJECT_DIR/docker/traefik/letsencrypt/acme.json
    - docker-compose -f docker-compose.yml -f docker-compose.production.yml -f docker-compose.engineer.yml build
    - docker-compose -f docker-compose.yml up -d traefik postgres redis_oauth redis_cable redis_cache rails elastic
    - docker-compose -f docker-compose.yml run --rm rails bundle exec rake db:test:load
    - docker-compose -f docker-compose.yml run --rm rails bundle exec rspec
    - docker-compose -f docker-compose.yml -f docker-compose.engineer.yml run --rm alpine sh -c "curl https://\$DOMAIN_NAME"
    - docker-compose -f docker-compose.yml run --rm puppeteer
  tags:
    - docker