version: "3.7"

services:

  puppeteer:
    env_file:
      - .env
    networks:
      hub:
        aliases:
          - puppeteer
    build:
      context: .
      dockerfile: ./docker/puppeteer/Dockerfile
      cache_from:
        - ${CI_REGISTRY}/woto/hub/puppeteer
        - ${CI_REGISTRY}/woto/hub/puppeteer:latest
        - ${CI_REGISTRY}/woto/hub/puppeteer:${version}
    image: ${CI_REGISTRY}/woto/hub/puppeteer:${version:-latest}
    ports:
      - "9229:9229"

networks:
  hub:
