version: "3.7"

services:

  postgres:
    ports:
      - ${POSTGRES_PORT}:5432

  redis_cable:
    ports:
      - ${REDIS_CABLE_PORT}:6379

  redis_cache:
    ports:
      - ${REDIS_CACHE_PORT}:6379

  redis_oauth:
    ports:
      - ${REDIS_OAUTH_PORT}:6379

  redis_sidekiq:
    ports:
      - ${REDIS_SIDEKIQ_PORT}:6379

  mongo:
    ports:
      - ${MONGO_PORT}:27017

  elastic:
    ports:
      - ${ELASTIC_REST_PORT}:9200
      - ${ELASTIC_CLUSTER_PORT}:9300

  mailcatcher:
    ports:
      - ${MAILCATCHER_WEB_PORT}:1080
      - ${MAILCATCHER_SMTP_PORT}:1025
