version: "3.7"

services:

  rails:
    volumes:
      - ".:/usr/src/app"

  puppeteer:
    volumes:
      - "./docker/puppeteer:/puppeteer"
  redis_cable:
    ports:
      - ${REDIS_CABLE_PORT}:6379

  redis_cache:
    ports:
      - ${REDIS_CACHE_PORT}:6379

  redis_oauth:
    ports:
      - ${REDIS_OAUTH_PORT}:6379

