version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
  postgres:
    image: postgres
    env_file:
      - .env
  rails:
    build: .
    command: bin/rails s -p 3000 -b '0.0.0.0' --pid /tmp/server.pid
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    stdin_open: true
    tty: true
