version: "3.7"
services:

  rails:
    env_file:
      - .env
    networks:
      hub:
        aliases:
          - rails
    build:
      context: .
      args:
        - RAILS_ENV=${HUB_ENV}
        - NODE_ENV=${HUB_ENV}
        - DOMAIN_NAME
        - SECRET_KEY_BASE
      target: ${RAILS_IMAGE_TARGET}
      cache_from:
        - ${CI_REGISTRY}/woto/hub/rails
        - ${CI_REGISTRY}/woto/hub/rails:latest
        - ${CI_REGISTRY}/woto/hub/rails:${version}
    image: ${CI_REGISTRY}/woto/hub/rails:${version:-latest}
    command:
      [
        "sh",
        "-c",
        "rm -f /tmp/server.pid && bin/rails s -b '0.0.0.0' --pid /tmp/server.pid",
      ]
    expose:
      - 3000
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.main_domain.entrypoints=websecure"
      - "traefik.http.routers.main_domain.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.main_domain.rule=Host(`${DOMAIN_NAME}`)"

      - "traefik.http.routers.ru.entrypoints=websecure"
      - "traefik.http.routers.ru.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.ru.rule=Host(`ru.${DOMAIN_NAME}`)"

      - "traefik.http.routers.en.entrypoints=websecure"
      - "traefik.http.routers.en.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.en.rule=Host(`en.${DOMAIN_NAME}`)"

      - "traefik.http.routers.zh.entrypoints=websecure"
      - "traefik.http.routers.zh.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.zh.rule=Host(`zh.${DOMAIN_NAME}`)"

  sidekiq:
    env_file:
      - .env
    image: ${CI_REGISTRY}/woto/hub/rails:${version:-latest}
    command:
      [
        "bundle",
        "exec",
        "sidekiq"
      ]

networks:
  hub:
