version: "3.7"

services:

  postgres:
    ports:
      - ${POSTGRES_PORT}:5432

  redis:
    ports:
      - ${REDIS_PORT}:6379

  elastic:
    ports:
      - ${ELASTIC_REST_PORT}:9200
      - ${ELASTIC_CLUSTER_PORT}:9300

  mailcatcher:
    ports:
      - ${MAILCATCHER_WEB_PORT}:1080
      - ${MAILCATCHER_SMTP_PORT}:1025
