version: "3.7"

services:

  # FOR DEBUGGING
  # to get into docker-compose network and for example
  # execute `docker-compose run --rm alpine sh -c "curl https://\$DOMAIN_NAME"
  # domain name passes from .env* files

  alpine:
    build:
      context: ./docker/alpine
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.${HUB_ENV}
    networks:
      hub:
        aliases:
          - alpine
    command: echo "Alpine image is used for debugging purposes only. Run it as `docker-compose run --rm alpine sh` to get network access to other containers."
    stdin_open: true
    tty: true