version: "3.7"

services:

  # To get into docker-compose network and for example
  # execute `docker-compose run --rm alpine sh -c "curl https://\$DOMAIN_NAME"
  # domain name passes from .env* files

  alpine:
    env_file:
      - .env
    networks:
      hub:
        aliases:
          - alpine
    build:
      context: ./docker/alpine
      dockerfile: Dockerfile
      cache_from:
        - registry.gitlab.com/woto/hub/alpine:${version:-latest}
    image: registry.gitlab.com/woto/hub/alpine:${version:-latest}
    command: echo "Alpine image is used for debugging purposes only. Run it as `docker-compose run --rm alpine sh` to get network access to other containers."
    stdin_open: true
    tty: true
