version: "3.7"
services:

  sidekiq:
    env_file:
      - .env
    networks:
      hub:
        aliases:
          - sidekiq
    image: ${CI_REGISTRY}/woto/hub/rails:${version:-latest}
    command:
      [
        "bundle",
        "exec",
        "sidekiq",
        "-C",
        "config/sidekiq"
      ]

networks:
  hub:
