version: "3.7"
services:

  scrapper:
    env_file:
      - .env
    build:
      context: ./docker/scrapper
      dockerfile: Dockerfile
    ports:
      - ${SCRAPPER_PORT}:4000

  iframely:
    env_file:
      - .env
    build:
      context: ./docker/iframely
      dockerfile: Dockerfile
    ports:
      - ${IFRAMELY_PORT}:8061

  elastic:
    env_file:
      - .env
    image: elasticsearch:7.10.1
    ports:
      - ${ELASTIC_REST_PORT}:9200
      - ${ELASTIC_CLUSTER_PORT}:9300
    environment:
      - discovery.type=single-node
      - path.repo=/tmp
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
    volumes:
      - elastic:/usr/share/elasticsearch/data

  kibana:
    env_file:
      - .env
    image: kibana:7.9.2
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200

  postgres:
    env_file:
      - .env
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - "postgres:/var/lib/postgresql/data"

  redis:
    env_file:
      - .env
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - "redis:/data"

  mailcatcher:
    env_file:
      - .env
    image: schickling/mailcatcher
    ports:
      - ${MAILCATCHER_WEB_PORT}:1080
      - ${MAILCATCHER_SMTP_PORT}:1025

volumes:
  redis:
  postgres:
  elastic:
