version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  test:
    docker:
      - image: cimg/ruby:3.2.1-browsers
      - image: redis
      - image: elasticsearch:8.7.0
        environment:
          node.name: hub
          discovery.type: single-node
          cluster.name: hub
          bootstrap.memory_lock: 'true'
          ES_JAVA_OPTS: -Xms512m -Xmx512m
          xpack.security.enabled: false
          action.destructive_requires_name: false
      - image: postgres:15.2
        environment:
          POSTGRES_USER: hub
          POSTGRES_DB: hub_test
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      RAILS_ENV: test
      NODE_ENV: test
      DB_USER: hub
      DB_HOST: localhost
      DB_NAME: hub_test
      DB_PASSWORD: 'Vet:orget5'
    executor: ruby/default
    steps:
      - run: ruby --version
      - run: node --version
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client libvips libvips-tools libvips-dev ffmpeg
      - run: gem update bundler
      - run: yarn install --pure-lockfile
#      - run:
#          name: Which bundler?
#          command: bundle -v
      - ruby/bundle-install
      - run: bundle exec rake assets:precompile
      - run:
          name: Setup PostgreSQL test database
          command: bin/rails db:test:prepare RAILS_ENV=test
      - run:
          name: Run tests
          command: bundle exec rspec --format documentation
