 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/template3s", type: :request do
  # Template3. As you add validations to Template3, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Template3.create! valid_attributes
      get template3s_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      template3 = Template3.create! valid_attributes
      get template3_url(template3)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_template3_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      template3 = Template3.create! valid_attributes
      get edit_template3_url(template3)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Template3" do
        expect {
          post template3s_url, params: { template3: valid_attributes }
        }.to change(Template3, :count).by(1)
      end

      it "redirects to the created template3" do
        post template3s_url, params: { template3: valid_attributes }
        expect(response).to redirect_to(template3_url(Template3.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Template3" do
        expect {
          post template3s_url, params: { template3: invalid_attributes }
        }.to change(Template3, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post template3s_url, params: { template3: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested template3" do
        template3 = Template3.create! valid_attributes
        patch template3_url(template3), params: { template3: new_attributes }
        template3.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the template3" do
        template3 = Template3.create! valid_attributes
        patch template3_url(template3), params: { template3: new_attributes }
        template3.reload
        expect(response).to redirect_to(template3_url(template3))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        template3 = Template3.create! valid_attributes
        patch template3_url(template3), params: { template3: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested template3" do
      template3 = Template3.create! valid_attributes
      expect {
        delete template3_url(template3)
      }.to change(Template3, :count).by(-1)
    end

    it "redirects to the template3s list" do
      template3 = Template3.create! valid_attributes
      delete template3_url(template3)
      expect(response).to redirect_to(template3s_url)
    end
  end
end
