default: &default
  adapter: redis
  host: <%= ENV['REDIS_HOST'] %>
  port: <%= ENV['REDIS_PORT'] %>

development:
  <<: *default
  db: 0
  channel_prefix: hub_development

test:
  <<: *default
  db: 1
  channel_prefix: hub_test

production:
  <<: *default
  db: 2
  channel_prefix: hub_production
