default: &default
  <<: *default
  adapter: redis
  host: <%= ENV['REDIS_CABLE_HOST'] %>
  port: <%= ENV['REDIS_CABLE_PORT'] %>

development:
  <<: *default
  db: 0
  channel_prefix: hub_development

test:
  <<: *default
  db: 1
  channel_prefix: hub_test

staging:
  <<: *default
  db: 2
  channel_prefix: hub_staging

production:
  <<: *default
  db: 3
  channel_prefix: hub_production
