development:
  adapter: redis
  url: redis://redis_cable:6379/0
  channel_prefix: hub_development

test:
  adapter: redis
  url: redis://redis_cable:6379/1
  channel_prefix: hub_test

staging:
  adapter: redis
  url: redis://redis_cable:6379/2
  channel_prefix: hub_staging

production:
  adapter: redis
  url: redis://redis_cable:6379/3
  channel_prefix: hub_production
