default: &default
  adapter: redis
  host: <%= ENV['REDIS_HOST'] %>
  port: <%= ENV['REDIS_PORT'] %>

development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  <<: *default
  channel_prefix: hub_production
