default: &default
  adapter: redis
  host: <%= ENV['REDIS_HOST'] %>
  port: <%= ENV['REDIS_PORT'] %>

development:
  adapter: async

test:
  adapter: test

production:
  <<: *default
  channel_prefix: hub_production
