default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: postgres

development:
  <<: *default
  database: hub_development

test:
  <<: *default
  database: hub_test

production:
  <<: *default
  database: hub_production
