# TODO: move into env variable because of separation of different
# environments were made based on index names
default: &default
  url: 'http://elastic:9200'
  log: false

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default