# TODO: move into env variable because of separation of different
# environments were made based on index names
default: &default
  host: <%= ENV['ELASTIC_HOST'] %>
  port: <%= ENV['ELASTIC_REST_PORT'] %>
  log: <%= ENV['ELASTIC_LOG'] %>
  trace: <%= ENV['ELASTIC_TRACE'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
