default: &default
  host: <%= ENV['ELASTIC_HOST'] %>
  port: <%= ENV['ELASTIC_REST_PORT'] %>
  log: <%= ENV['ELASTIC_LOG'] %>
  trace: <%= ENV['ELASTIC_TRACE'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
