default: &default
  currencies:
    rub: 643
    eur: 978
    usd: 840
  cost_per_character_rub: 0.03
  post_extra_options:
    some_radio:
      type: radio_buttons
      values:
        - title: rewrite
          rate: 1
        - title: copywrite
          rate: 1.03
    some_checkbox:
      type: check_boxes
      values:
        - title: 1
          rate: 1
        - title: 2
          rate: 1.01
        - title: 3
          rate: 1.02

  blank_messenger:
    short: select ...
    long: Select ...

  locales:
    -
      locale: 'en-GB'
      title: 'English GB'
    -
      locale: 'en-US'
      title: 'English US'
    -
      locale: 'en'
      title: 'English General'
    -
      locale: 'zh-CN'
      title: '中文'
    -
      locale: 'ja'
      title: '日本語'
    -
      locale: 'es'
      title: 'Español'
    -
      locale: 'de'
      title: 'Deutsch'
    -
      locale: 'fr'
      title: 'Français'
    -
      locale: 'ko'
      title: '한국어'
    -
      locale: 'pt'
      title: 'Português'
    -
      locale: 'it'
      title: 'Italiano'
    -
      locale: 'ru'
      title: 'Русский'

  messengers:
    -
      short: whatsapp
      long: WhatsApp
    -
      short: viber
      long: Viber
    -
      short: wechat
      long: WeChat
    -
      short: qq_mobile
      long: QQ Mobile
    -
      short: telegram
      long: Telegram
    -
      short: skype
      long: Skype
    -
      short: email
      long: E-mail
    -
      short: mobile_phone
      long: Mobile Phone

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
