common: &default_settings
  pushgateway_address: <%= "http://localhost:#{ENV['PUSHGATEWAY_PORT']}" %>

development:
  <<: *default_settings

test:
  <<: *default_settings

production:
  <<: *default_settings
