default: &default
  host: <%= ENV['REDIS_HOST'] %>
  host: <%= ENV['REDIS_HOST'] %>

development:
  <<: *default
  db: 0

test:
  <<: *default
  db: 1

staging:
  <<: *default
  db: 2

production:
  <<: *default
  db: 3
