default: &default
  host: <%= ENV['REDIS_SIDEKIQ_HOST'] %>
  port: <%= ENV['REDIS_SIDEKIQ_PORT'] %>

development:
  <<: *default
  db: 0

test:
  <<: *default
  db: 1

staging:
  <<: *default
  db: 2

production:
  <<: *default
  db: 3
