default: &default
  host: <%= ENV['REDIS_OAUTH_HOST'] %>
  port: <%= ENV['REDIS_OAUTH_PORT'] %>

development:
  <<: *default
  db: 0

test:
  <<: *default
  db: 1

staging:
  <<: *default
  db: 2

production:
  <<: *default
  db: 3
