---
:concurrency: 5
production:
  :concurrency: 20
:queues:
  - active_storage_analysis
  - action_mailbox_routing
  - mailers
  - default

:schedule:
  prometheus:
    cron: '0 * * * * *'   # Runs once per minute
    class: PrometheusJob
