---
:concurrency: 5
production:
  :concurrency: 20
:queues:
  - critical
  - default
  - low
  - action_mailbox_routing
  - action_mailbox_incineration
  - active_storage_analysis
  - active_storage_purge

:schedule:
  prometheus:
    cron: '0 * * * * *'   # Runs once per minute
    class: PrometheusJob
  active_storage_purge:
    cron: '* 0 * * * *'   # Runs once per hour
    class:
