global:
  # How frequently to scrape targets
  scrape_interval: 5s
  # How frequently to evaluate rules
  evaluation_interval: 5s

# Rules and alerts are read from the specified file(s)
rule_files:
  - rules.yml

# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            # Alertmanager's default port is 9093
            - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "rails"
    static_configs:
      - targets: ["rails:9394"]

  - job_name: "sidekiq"
    static_configs:
      - targets: ["sidekiq:9394"]

  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
