# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "activerecord", "~> 7.0"
gem "telegram-bot-ruby"
gem "byebug", "~> 11.1"
gem "pg", "~> 1.3"
gem "activesupport", "~> 7.0"
gem "faraday-multipart", "~> 1.0"
gem "typhoeus", "~> 1.4"
gem "faraday-typhoeus", "~> 0.2.0"
gem "httpx", "~> 0.19.8"
