name: github

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    env:
      RAILS_ENV: test
      NODE_ENV: test

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.2
        ports: ['5432:5432']
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: hub
          POSTGRES_PASSWORD: Vet:orget5
          POSTGRES_DB: hub
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

      elastic:
        ports: ['9200:9200', '9300:9300']
        env:
          discovery.type: single-node
          xpack.security.enabled: false
          action.destructive_requires_name: false
        image: elasticsearch:8.7.0

    steps:

    - name: Update Ubuntu repositories
      run: sudo apt-get update

    - name: Install libvips
      run: sudo apt-get install libvips libvips-tools libvips-dev ffmpeg

    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.1

    - name: Ruby gem cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.12.1

    - name: Find yarn cache location
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: JS package cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install packages
      run: |
        yarn install --pure-lockfile

    - name: Compile assets
      run: bundle exec rake assets:precompile

    - name: Setup DB
      run: bin/rails db:create db:schema:load

    - name: Run tests
      run: bundle exec rspec --format documentation

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: rspec_logs
        path: ./log

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: failed_screenshots
        path: ./tmp/screenshots
